services:
  backend:
    build:
      context: .
    volumes:
      - ..:/app
    ports:
      - ${APP_PORT}:${APP_PORT}
    working_dir: /app
    command:
      - sh
      - -c
      - |
        npm install
        sleep infinity
  # db:
  #   image: postgres:14.3
  #   ports:
  #     - 5432:5432
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: 123456
  #     POSTGRES_DB: app
