name: Test & Coverage

on:
  workflow_call:


jobs:
  test:
    steps:
      - name: 💡 Run tests with coverage
        run: |
          docker compose --env-file .env.dev -f docker/docker-compose-dev.yml exec backend bash -c "npm run test"
